# @name getEvents
GET http://localhost:3001/eventos

###
# @name createEvent
POST http://localhost:3001/eventos
Content-Type: application/json

{
  "name": "Novo evento",
  "description": "Esse é um novo evento",
  "date":"2017-01-01T00:00:00.00",
  "price": 50
}

###

@eventId = {{createEvent.response.body.id}}

###
# @name getSingleEvent
GET http://localhost:3001/eventos/{{eventId}}

###
# @name updateEvent
PATCH http://localhost:3001/eventos/{{eventId}}
Content-Type: application/json

{
  "name": "Novo Evento",
  "description": "Esse é um novo evento",
  "date":"2017-01-01T00:00:00.00"
}

###
# @name deleteEvent
DELETE http://localhost:3001/eventos/{{eventId}}

###
# @name getSpots
GET http://localhost:3001/eventos/{{eventId}}/lugares

###
# @name createSpot
POST http://localhost:3001/eventos/{{eventId}}/lugares
Content-Type: application/json

{
  "name": "A3"
}

###
# @name reserveSpots
POST http://localhost:3001/eventos/{{eventId}}/reserva
Content-Type: application/json

{
  "spots": ["A2", "A3"],
  "ticket_kind": "full",
  "email": "teste@email.com"
}